load('XTrain.mat');
load('YTrain.mat');
load('CTRLNet_512.mat');

options = trainingOptions('sgdm', ...
    'Momentum',0.9, ...
    'InitialLearnRate',1e-3, ...
    'L2Regularization',0.0005, ...
    'MaxEpochs',10000, ...  
    'MiniBatchSize',5, ...
    'Shuffle','every-epoch', ...
    'VerboseFrequency',2, ...
    'ExecutionEnvironment','multi-gpu');

[net,info] = trainNetwork(XTrain,YTrain,CTRLNet_512,options);

save('net.mat','net');
save('info.mat','info');